name: pasternak_frontend
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  provider: ^6.1.1
  web_smooth_scroll: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  
  assets:
    - assets/categories.json
    - assets/chunk_hypotheses.json
    - assets/hypotheses.json
    - assets/letter_chunks.json
    - assets/letter_composites.json
    - assets/letters.json
  
  fonts:
    - family: Open Sans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
    - family: PT Serif
      fonts:
        - asset: assets/fonts/PTSerif-Regular.ttf
        - asset: assets/fonts/PTSerif-Italic.ttf
          style: italic
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Regular.ttf
        - asset: assets/fonts/Merriweather-Italic.ttf
          style: italic

  uses-material-design: true

